services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  # Serwis zarządzania połączeniami Redis
  psredis.service.connection:
    class: Psredis\Service\RedisConnectionService
    file: '%kernel.project_dir%/modules/psredis/src/Service/RedisConnectionService.php'
    arguments:
      - '%kernel.project_dir%/modules/psredis'
    public: true

  # Adapter Cache Redis
  psredis.cache.adapter:
    class: Psredis\Cache\RedisCacheAdapter
    file: '%kernel.project_dir%/modules/psredis/src/Cache/RedisCacheAdapter.php'
    arguments:
      - '@psredis.service.connection'
    public: true

  # Subskrybent zdarzeń do automatycznego czyszczenia cache
  psredis.hook.subscriber:
    class: Psredis\Hook\CacheHookSubscriber
    file: '%kernel.project_dir%/modules/psredis/src/Hook/CacheHookSubscriber.php'
    arguments:
      - '@psredis.cache.adapter'
    tags:
      - { name: hook.subscriber }

  # Komenda Konsolowa (CRON)
  Psredis\Command\CacheWarmupCommand:
    class: Psredis\Command\CacheWarmupCommand
    file: '%kernel.project_dir%/modules/psredis/src/Command/CacheWarmupCommand.php'
    tags:
      - { name: console.command, command: 'psredis:cache:warmup' }
    public: true

  # ----------------------------------------------------
  # Zastąpienie Domyślnego Systemu Cache (Opcjonalne, poza plikiem services.yml)
  # ----------------------------------------------------
  # Jeśli potrzebujesz użyć tego adaptera jako głównego cache (np. w PrestaShop), 
  # musisz zdefiniować alias dla domyślnego serwisu cache (np. 'cache' lub 
  # 'cache.adapter') w innym pliku konfiguracyjnym (np. override), 
  # aby wskazywał na '@psredis.cache.adapter'.